### ISSUE TITLE
Shishi: Fails to patch png images folder ripped with Shishi

### ISSUE THREAD

**Issue by invadermonks** [Glain/FFTPatcher#23]
Shishi give the following error trying to patch other images ripped directly from a clean twotl image with Image->Export all images (PNG):

start /wait "Patch" ShishiSpriteEditor.exe -expand -patch "data\bugtest1\shishi_import" "output\fft_1685390729.bin"
Error: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

This works fine with png images from exported from TLW, but not with the ones from TLWotL - it may have to do with the number (222 images in TLWotL vs 63 in TLW). Here is the images folder that fails:

[bugtest1_shishi_import.zip](https://github.com/Glain/FFTPatcher/files/11593953/bugtest1_shishi_import.zip)

**Comment by Glain** [comment]
@invadermonks There should now be a more descriptive error message with commit c668a9a.  However, your input file is strange in numerous ways:

* There should have been 1379 images exported, not 222 or 63.  
* Several of the images exported (particularly from EVTFACE) have an extra white color at the end of the palette (causing an error attempting to import).
* The EVTFACE images have somehow exported as 8bpp images instead of 4bpp images.  

I tried extracting the TLWotL images with Shishi, and these issues did not happen for me.

**Comment by invadermonks** [comment]
The 222 and 63 were the number of changed images, not the total number of images. I tested this again with the current revision of the code and it works perfectly, not sure how the export messed up before. New error messages are great. Thanks!
